Repository AGH-Narzedzia-Informatyczne-2022-2023/FriendBy, pull requests merged in 2022-11, with the labels that each got.

#16 branche
  funkcjonalnosc.txt
Labels: documentation

#21 Create funkcjonalność2.txt
  funkcjonalność2.txt
Labels: good first issue

#20 pyqt
  o_pyqt.txt
Labels: enhancement

#19 Create README Serhii Zeliuk
  README Serhii Zeliuk
Labels: Grafika
